[package]
name = "xiron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parry2d = "0.12.0"
macroquad = "0.3.25"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0.94"
zmq = "0.10.0"
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
argparse = "0.2.2"

[build-dependencies]
tonic-build = "0.9"

[[bin]]
name = "world_editor"

[[bin]]
name = "simulator"

[[bin]]
name = "renderer"

[[example]]
name = "grpc_client"

[[example]]
name = "path_tracking"

[[example]]
name = "keyboard_input"
