robots:
  - id: robot0
    pose: [0.0, 0.0, 0.0]
    vel: [0.0, 0.0]

walls:
  - endpoints:
    - [3.0, 1.0]
    - [3.0, 5.0]
    - [10.0, 5.0]

  - endpoints:
    - [-3.0, -1.0]
    - [-3.0, -5.0]
    - [-10.0, -5.0]