# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x10xiron_interfaces\"3\n\x0fVelocityRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01v\x18\x02 \x01(\x01\x12\t\n\x01w\x18\x03 \x01(\x01\"\x1f\n\x10VelocityResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x19\n\x0bPoseRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0cPoseResponse\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\x32\xb0\x01\n\x0eXironInterface\x12T\n\x0bSetVelocity\x12!.xiron_interfaces.VelocityRequest\x1a\".xiron_interfaces.VelocityResponse\x12H\n\x07GetPose\x12\x1d.xiron_interfaces.PoseRequest\x1a\x1e.xiron_interfaces.PoseResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VELOCITYREQUEST._serialized_start=37
  _VELOCITYREQUEST._serialized_end=88
  _VELOCITYRESPONSE._serialized_start=90
  _VELOCITYRESPONSE._serialized_end=121
  _POSEREQUEST._serialized_start=123
  _POSEREQUEST._serialized_end=148
  _POSERESPONSE._serialized_start=150
  _POSERESPONSE._serialized_end=201
  _XIRONINTERFACE._serialized_start=204
  _XIRONINTERFACE._serialized_end=380
# @@protoc_insertion_point(module_scope)
